#!/usr/bin/env python

import glob

coverageFiles = glob.glob( "*.coverage.xml" )

print "Submitting coverage files"

for f in coverageFiles[:1] :
	os.system( "cp {} coverage.xml".format( f ) )

os.system( "python-codacy-coverage -r coverage.xml" )
